name: superwallkit_flutter
description: "Remotely configure every aspect of your paywall and double your revenue."
version: 2.3.4
homepage: "https://superwall.com"

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  pigeon: 22.7.2
  plugin_platform_interface: ^2.0.2
  uuid: ^4.4.0
  yaml: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

dependency_overrides:
  dart_style: ^3.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.superwall.superwallkit_flutter
        pluginClass: SuperwallkitFlutterPlugin
      ios:
        pluginClass: SuperwallkitFlutterPlugin

  assets:
    - pubspec.yaml
