name: Tag new version

on:
  push:
    branches: [main]

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Tag
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name 'Jake'
          git config --global user.email 'jakemor@users.noreply.github.com'
          
          echo "\n\n\n- - - - - VERSION - - - - -\n\n\n"
          VERSION=$(grep '^version:' pubspec.yaml | awk '{ print $2 }')
          echo $VERSION
          echo "\n\n\n- - - - - END VERSION - - - - -\n\n\n"
          
          git tag -a "$VERSION" -m "tags with latest version"
          
          git remote set-url origin https://x-access-token:$GH_PAT@github.com/${{ github.repository }}
          git push origin "$VERSION"
          
          git checkout -b "release/$VERSION"
          git push -u origin "release/$VERSION"
