name: Tag new version

on:
  push:
    branches: [main]

jobs:
  dry_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: stable

      - name: Get dependencies
        run: flutter pub get

      - name: Dry run pub publish
        run: flutter pub publish --dry-run

  tag:
    needs: dry_run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Tag
        run: |
          sudo git config --global user.name 'Jake'
          sudo git config --global user.email 'jakemor@users.noreply.github.com'
          sudo git pull
          echo "\n\n\n- - - - - VERSION - - - - -\n\n\n"
          VERSION=$(grep '^version:' pubspec.yaml | awk '{ print $2 }')
          echo $VERSION
          echo "\n\n\n- - - - - END VERSION - - - - -\n\n\n"
          sudo git tag -a "$VERSION" -m "tags with latest version"
          sudo git push --tags || true
          sudo git checkout -b "release/$VERSION"
          sudo git push -u origin "release/$VERSION"
